[package]
name = 'image'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[lib]
path = 'lib.rs'

[dependencies]
num = { path = '../num', optional = true }
iter = { path = '../iter' }
vector = { path = '../vector' }
xy = { path = '../xy' }
fehler = ''

[profile.dev] # Optimize fill,set_map,from_linear
opt-level = 2
