package={name= 'image', version= '0.0.0', edition= '2021', rust-version='1.80'}
lib={path= 'lib.rs'}
[features]
type_alias_impl_trait=[]
slice_take=[]
new_uninit=[]
const_trait_impl=[]
unstable=['type_alias_impl_trait','slice_take','new_uninit','const_trait_impl']
io = ['image']
png = ['dep:png','byteorder']

[dependencies]
num={git='https://github.com/Matthias-Fauconneau/num'}
vector={git='https://github.com/Matthias-Fauconneau/vector'}
bytemuck='*'
image={version='*', default-features=false, features=['png','jpeg'], optional=true}
png={version='*', optional=true}
byteorder={version='*', optional=true}
