package={name= 'image', version= '0.0.0', edition= '2021'}
lib= {path= 'lib.rs'}

[dependencies]
num= {git='https://github.com/Matthias-Fauconneau/num'}
vector= {git='https://github.com/Matthias-Fauconneau/vector'}
bytemuck='*'
