[package]
name = 'image'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2021'

[dependencies]
num= {git='https://github.com/Matthias-Fauconneau/num'}
iter = {git='https://github.com/Matthias-Fauconneau/iter'}
vector = {git='https://github.com/Matthias-Fauconneau/vector'}
bytemuck = '*'

[lib]
path = 'lib.rs'

[profile.dev] # Optimize fill,set_map,from_linear
opt-level = 3
overflow-checks = false
