[package]
name = 'image'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
sRGB = ['core/array']
default = ['sRGB']

[dependencies]
cfg-if = ''
xy = { version = '', path = '../xy' }
core = { version = '', path = '../core' }

[profile.dev] # Optimize fill,set_map,from_linear
opt-level = 2
